### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by shazow** [shazow/nixfiles#3]
Trying to do:

https://nixos.org/nixos/manual/index.html#sec-installing-from-other-distro

~~Using [hosts/shazowic-corvus.nix](https://github.com/shazow/nixfiles/blob/master/hosts/shazowic-corvus.nix) as configuration.nix (the README in the repo has more details about the general setup).~~ Also reproduced with a trivial configuration.nix (see below)

I get this error:

```console
$ nixos-install --no-bootloader --root /mnt/rootnix --show-trace
building the configuration in /mnt/rootnix/etc/nixos/configuration.nix...
error: while setting up the build environment: getting attributes of path '': No such file or directory
```

How do I debug where the '' is coming from?

**Edit**: Seems it's a problem with nixos-install when using the nix installed on Arch on aur/nix, see comments.

**Comment by ottidmes** [comment]
Guessing from the configuration you linked I would say it either has to be `disk.disk.extraInitrd` or `disk.keyFile`:
https://github.com/shazow/nixfiles/blob/master/common/boot.nix#L30
https://github.com/shazow/nixfiles/blob/master/common/boot.nix#L39-L49

**Comment by shazow** [comment]
@ottidmes Hm, any suggestions for how to better debug these kinds of problems aside from trial and error?

FWIW my `disk.nix` looks like this: https://github.com/shazow/nixfiles/blob/master/disk.example.nix

**Comment by shazow** [comment]
I'm assuming it has to do with some path string being empty where it shouldn't be, but I tried hardcoding practically everything in boot.nix and still no luck. Wish I could find out what variable it's failing at.

**Comment by shazow** [comment]
Hm, even a purely minimal `configuration.nix` that was autogenerated fails the same way.

Example of the smallest config:

```nix
{ config, pkgs, ... }:

{
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;
  system.stateVersion = "18.09";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3af5b147-3f68-4a9f-98f1-714df2d45c94";
      fsType = "btrfs";
      options = [ "subvol=@rootnix" ];
    };
}
```

```console
$ nixos-install --no-bootloader --root /mnt/rootnix
building the configuration in /mnt/rootnix/etc/nixos/configuration.nix...
[2 copied (36.8 MiB), 0.0 MiB DL]
error: while setting up the build environment: getting attributes of path '': No such file or directory
```

**Comment by shazow** [comment]
Confirmed that this must be related to using https://aur.archlinux.org/packages/nix/ instead of nix from the bash-curl installer.

Tried the same thing with the bash-curl installer and it worked.
